# Form implementation generated from reading ui file 'create-client-window.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(255, 225)
        MainWindow.setMinimumSize(QtCore.QSize(255, 225))
        MainWindow.setMaximumSize(QtCore.QSize(255, 225))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("#centralwidget{\n"
"background-color: #131936;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.name_edit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.name_edit.setMinimumSize(QtCore.QSize(0, 30))
        self.name_edit.setStyleSheet("#name_edit{\n"
"    background-color: transparent;\n"
"    border: 1px solid gray; \n"
"    color: white;\n"
"}")
        self.name_edit.setMaxLength(30)
        self.name_edit.setObjectName("name_edit")
        self.gridLayout_2.addWidget(self.name_edit, 0, 0, 1, 1)
        self.surname_edit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.surname_edit.setMinimumSize(QtCore.QSize(0, 30))
        self.surname_edit.setStyleSheet("#surname_edit{\n"
"    background-color: transparent;\n"
"    border: 1px solid gray;\n"
" color: white;\n"
"}")
        self.surname_edit.setMaxLength(30)
        self.surname_edit.setObjectName("surname_edit")
        self.gridLayout_2.addWidget(self.surname_edit, 1, 0, 1, 1)
        self.secondname_edit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.secondname_edit.setMinimumSize(QtCore.QSize(0, 30))
        self.secondname_edit.setStyleSheet("#secondname_edit{\n"
"    background-color: transparent;\n"
"    border: 1px solid gray;\n"
" color: white;\n"
"}")
        self.secondname_edit.setMaxLength(30)
        self.secondname_edit.setObjectName("secondname_edit")
        self.gridLayout_2.addWidget(self.secondname_edit, 2, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.tel_edit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.tel_edit.setMinimumSize(QtCore.QSize(0, 25))
        self.tel_edit.setStyleSheet("#tel_edit{\n"
"    background-color: transparent;\n"
"    border: 1px solid gray;\n"
" color: white;\n"
"}")
        self.tel_edit.setObjectName("tel_edit")
        self.gridLayout.addWidget(self.tel_edit, 0, 0, 1, 1)
        self.save_client_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.save_client_button.setMinimumSize(QtCore.QSize(100, 35))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight SemiConde")
        font.setPointSize(14)
        self.save_client_button.setFont(font)
        self.save_client_button.setStyleSheet("#save_client_button{\n"
"    background-color: rgb(24, 148, 2);\n"
"}")
        self.save_client_button.setObjectName("save_client_button")
        self.gridLayout.addWidget(self.save_client_button, 0, 1, 1, 1)
        self.datebirth_edit = QtWidgets.QDateEdit(parent=self.centralwidget)
        self.datebirth_edit.setMinimumSize(QtCore.QSize(0, 25))
        self.datebirth_edit.setStyleSheet("#datebirth_edit{\n"
"    background-color: transparent;\n"
"    border: 1px solid gray;\n"
" color: white;\n"
"}")
        self.datebirth_edit.setObjectName("datebirth_edit")
        self.gridLayout.addWidget(self.datebirth_edit, 1, 0, 1, 1)
        self.del_client_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.del_client_button.setMinimumSize(QtCore.QSize(100, 35))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight SemiConde")
        font.setPointSize(14)
        self.del_client_button.setFont(font)
        self.del_client_button.setStyleSheet("#del_client_button{\n"
"    background-color: rgba(255, 0, 0, 0.9);\n"
"}")
        self.del_client_button.setObjectName("del_client_button")
        self.gridLayout.addWidget(self.del_client_button, 1, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 3, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Клиент"))
        self.name_edit.setPlaceholderText(_translate("MainWindow", "Введите имя"))
        self.surname_edit.setPlaceholderText(_translate("MainWindow", "Введите фамилию"))
        self.secondname_edit.setPlaceholderText(_translate("MainWindow", "Введите отчество (при наличии)"))
        self.tel_edit.setInputMask(_translate("MainWindow", "+7-999-999-99-99"))
        self.save_client_button.setText(_translate("MainWindow", "Сохранить"))
        self.del_client_button.setText(_translate("MainWindow", "Удалить"))
