# Form implementation generated from reading ui file 'loyal-system-settings.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(340, 270)
        MainWindow.setMinimumSize(QtCore.QSize(340, 270))
        MainWindow.setMaximumSize(QtCore.QSize(340, 500))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("#centralwidget{\n"
"background-color: #131936;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.hour_count_label = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight SemiConde")
        font.setPointSize(14)
        self.hour_count_label.setFont(font)
        self.hour_count_label.setStyleSheet("#hour_count_label{\n"
"color: white;\n"
"}")
        self.hour_count_label.setObjectName("hour_count_label")
        self.gridLayout.addWidget(self.hour_count_label, 0, 0, 1, 1)
        self.discount_label = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight SemiConde")
        font.setPointSize(14)
        self.discount_label.setFont(font)
        self.discount_label.setStyleSheet("#discount_label{\n"
"color: white;\n"
"}")
        self.discount_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.discount_label.setObjectName("discount_label")
        self.gridLayout.addWidget(self.discount_label, 0, 1, 1, 1)
        self.condition_tab = QtWidgets.QTableWidget(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight SemiConde")
        font.setPointSize(12)
        self.condition_tab.setFont(font)
        self.condition_tab.setStyleSheet("#condition_tab{\n"
" background-color: transparent;\n"
"border: 1px solid white;\n"
"color: white;\n"
"}")
        self.condition_tab.setColumnCount(2)
        self.condition_tab.setObjectName("condition_tab")
        self.condition_tab.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.condition_tab.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.condition_tab.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.condition_tab.setItem(0, 1, item)
        self.condition_tab.horizontalHeader().setVisible(False)
        self.condition_tab.horizontalHeader().setDefaultSectionSize(100)
        self.condition_tab.verticalHeader().setVisible(False)
        self.condition_tab.verticalHeader().setDefaultSectionSize(32)
        self.condition_tab.setColumnWidth(0, 215)
        self.condition_tab.setColumnWidth(1, 104)
        self.gridLayout.addWidget(self.condition_tab, 1, 0, 1, 2)
        self.add_condition_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.add_condition_button.setMinimumSize(QtCore.QSize(320, 35))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight SemiConde")
        font.setPointSize(14)
        self.add_condition_button.setFont(font)
        self.add_condition_button.setStyleSheet("#add_condition_button{\n"
"    background-color: rgb(92, 17, 255);\n"
"color: white;\n"
"}")
        self.add_condition_button.setObjectName("add_condition_button")
        self.gridLayout.addWidget(self.add_condition_button, 2, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Система лояльности"))
        self.hour_count_label.setText(_translate("MainWindow", "Количество часов аренды"))
        self.discount_label.setText(_translate("MainWindow", "Скидка"))
        item = self.condition_tab.verticalHeaderItem(0)
        __sortingEnabled = self.condition_tab.isSortingEnabled()
        self.condition_tab.setSortingEnabled(False)
        item = self.condition_tab.item(0, 0)
        item = self.condition_tab.item(0, 1)
        self.condition_tab.setSortingEnabled(__sortingEnabled)
        self.add_condition_button.setText(_translate("MainWindow", "Добавить условие"))
