# Form implementation generated from reading ui file 'main-window.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(820, 680)
        MainWindow.setMinimumSize(QtCore.QSize(820, 680))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        MainWindow.setStyleSheet("#MainWindow{\n"
"border: none;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setStyleSheet("#centralwidget{\n"
"background-color: #131936;\n"
"border:none;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(800, 660))
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight SemiConde")
        font.setPointSize(16)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("QTabBar::tab {\n"
"    min-width: 205px;\n"
"    height: 90px;\n"
"    background-color: rgb(41, 85, 180);\n"
"    color: white;\n"
"    border: 0px solid transparent;\n"
"    margin: 0px;\n"
"    padding: 0px;\n"
"}\n"
"QTabBar::tab:selected {\n"
"    background-color: #131936;\n"
"    color: white;\n"
"    border: none;\n"
"}")
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.TabShape.Rounded)
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setObjectName("tabWidget")
        self.game_session_tab = QtWidgets.QWidget()
        self.game_session_tab.setStyleSheet("#game_session_tab{\n"
"background-color: #131936;\n"
"}\n"
"")
        self.game_session_tab.setObjectName("game_session_tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.game_session_tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.button_sessions_layout = QtWidgets.QHBoxLayout()
        self.button_sessions_layout.setObjectName("button_sessions_layout")
        self.create_session_button = QtWidgets.QPushButton(parent=self.game_session_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.create_session_button.sizePolicy().hasHeightForWidth())
        self.create_session_button.setSizePolicy(sizePolicy)
        self.create_session_button.setMinimumSize(QtCore.QSize(200, 60))
        self.create_session_button.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight SemiConde")
        font.setPointSize(14)
        self.create_session_button.setFont(font)
        self.create_session_button.setStyleSheet("#create_session_button{\n"
"    background-color: rgb(92, 17, 255);\n"
"color: white;\n"
"}")
        self.create_session_button.setObjectName("create_session_button")
        self.button_sessions_layout.addWidget(self.create_session_button)
        self.select_hall = QtWidgets.QComboBox(parent=self.game_session_tab)
        self.select_hall.setMinimumSize(QtCore.QSize(120, 60))
        self.select_hall.setMaximumSize(QtCore.QSize(120, 60))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight SemiConde")
        font.setPointSize(14)
        self.select_hall.setFont(font)
        self.select_hall.setStyleSheet("#select_hall{\n"
"    background-color: rgb(92, 17, 255);\n"
"color: white;\n"
"}")
        self.select_hall.setObjectName("select_hall")
        self.button_sessions_layout.addWidget(self.select_hall)
        self.loyal_system_button = QtWidgets.QPushButton(parent=self.game_session_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loyal_system_button.sizePolicy().hasHeightForWidth())
        self.loyal_system_button.setSizePolicy(sizePolicy)
        self.loyal_system_button.setMinimumSize(QtCore.QSize(200, 60))
        self.loyal_system_button.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight SemiConde")
        font.setPointSize(14)
        self.loyal_system_button.setFont(font)
        self.loyal_system_button.setStyleSheet("#loyal_system_button{\n"
"    background-color: rgb(92, 17, 255);\n"
"color: white;\n"
"}")
        self.loyal_system_button.setObjectName("loyal_system_button")
        self.button_sessions_layout.addWidget(self.loyal_system_button)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.button_sessions_layout.addItem(spacerItem)
        self.find_game_session = QtWidgets.QLineEdit(parent=self.game_session_tab)
        self.find_game_session.setMinimumSize(QtCore.QSize(245, 35))
        self.find_game_session.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight SemiConde")
        font.setPointSize(12)
        self.find_game_session.setFont(font)
        self.find_game_session.setStyleSheet("#find_game_session{\n"
"    background-color: transparent;\n"
"    border: 1px solid gray;\n"
"    color: white;\n"
"}")
        self.find_game_session.setPlaceholderText("Введите номер места или телефон")
        self.find_game_session.setObjectName("find_game_session")
        self.button_sessions_layout.addWidget(self.find_game_session)
        self.gridLayout_2.addLayout(self.button_sessions_layout, 0, 0, 1, 1)
        self.list_of_sessions = QtWidgets.QListWidget(parent=self.game_session_tab)
        self.list_of_sessions.setStyleSheet("#list_of_sessions{\n"
"    background-color: transparent;\n"
"    border: 1px solid gray;\n"
"    color: white;\n"
"}")
        self.list_of_sessions.setObjectName("list_of_sessions")
        self.gridLayout_2.addWidget(self.list_of_sessions, 1, 0, 1, 1)
        self.tabWidget.addTab(self.game_session_tab, "")
        self.client_tab = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight SemiConde")
        font.setPointSize(14)
        self.client_tab.setFont(font)
        self.client_tab.setStyleSheet("#client_tab{\n"
"background-color: #131936;\n"
"}")
        self.client_tab.setObjectName("client_tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.client_tab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.button_client_layout = QtWidgets.QHBoxLayout()
        self.button_client_layout.setObjectName("button_client_layout")
        self.create_client_button = QtWidgets.QPushButton(parent=self.client_tab)
        self.create_client_button.setMinimumSize(QtCore.QSize(200, 60))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight SemiConde")
        font.setPointSize(14)
        self.create_client_button.setFont(font)
        self.create_client_button.setStyleSheet("#create_client_button{\n"
"    background-color: rgb(92, 17, 255);\n"
"color: white;\n"
"}")
        self.create_client_button.setObjectName("create_client_button")
        self.button_client_layout.addWidget(self.create_client_button)
        spacerItem1 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.button_client_layout.addItem(spacerItem1)
        self.find_client = QtWidgets.QLineEdit(parent=self.client_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.find_client.sizePolicy().hasHeightForWidth())
        self.find_client.setSizePolicy(sizePolicy)
        self.find_client.setMinimumSize(QtCore.QSize(245, 35))
        self.find_client.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight SemiConde")
        font.setPointSize(12)
        self.find_client.setFont(font)
        self.find_client.setStyleSheet("#find_client{\n"
"    background-color: transparent;\n"
"    border: 1px solid gray;\n"
"    color: white;\n"
"}")
        self.find_client.setPlaceholderText("Введите фамилию или номер телефона")
        self.find_client.setObjectName("find_client")
        self.button_client_layout.addWidget(self.find_client)
        self.gridLayout_3.addLayout(self.button_client_layout, 0, 0, 1, 1)
        self.list_of_clients = QtWidgets.QListWidget(parent=self.client_tab)
        self.list_of_clients.setStyleSheet("#list_of_clients{\n"
"    background-color: transparent;\n"
"    border: 1px solid gray;\n"
"    color: white;\n"
"}")
        self.list_of_clients.setObjectName("list_of_clients")
        self.gridLayout_3.addWidget(self.list_of_clients, 1, 0, 1, 1)
        self.tabWidget.addTab(self.client_tab, "")
        self.equipment_tab = QtWidgets.QWidget()
        self.equipment_tab.setStyleSheet("#equipment_tab{\n"
"background-color: #131936;\n"
"}")
        self.equipment_tab.setObjectName("equipment_tab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.equipment_tab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.button_equipment_layout = QtWidgets.QHBoxLayout()
        self.button_equipment_layout.setObjectName("button_equipment_layout")
        self.create_equipment_button = QtWidgets.QPushButton(parent=self.equipment_tab)
        self.create_equipment_button.setMinimumSize(QtCore.QSize(200, 60))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight SemiConde")
        font.setPointSize(14)
        self.create_equipment_button.setFont(font)
        self.create_equipment_button.setStyleSheet("#create_equipment_button{\n"
"    background-color: rgb(92, 17, 255);\n"
"color: white;\n"
"}")
        self.create_equipment_button.setObjectName("create_equipment_button")
        self.button_equipment_layout.addWidget(self.create_equipment_button)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.button_equipment_layout.addItem(spacerItem2)
        self.find_equipment = QtWidgets.QLineEdit(parent=self.equipment_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.find_equipment.sizePolicy().hasHeightForWidth())
        self.find_equipment.setSizePolicy(sizePolicy)
        self.find_equipment.setMinimumSize(QtCore.QSize(245, 35))
        self.find_equipment.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight SemiConde")
        font.setPointSize(12)
        self.find_equipment.setFont(font)
        self.find_equipment.setStyleSheet("#find_equipment{\n"
"    background-color: transparent;\n"
"    border: 1px solid gray;\n"
"    color: white;\n"
"}")
        self.find_equipment.setPlaceholderText("Введите код устройства")
        self.find_equipment.setObjectName("find_equipment")
        self.button_equipment_layout.addWidget(self.find_equipment)
        self.gridLayout_4.addLayout(self.button_equipment_layout, 0, 0, 1, 1)
        self.list_of_equipment = QtWidgets.QListWidget(parent=self.equipment_tab)
        self.list_of_equipment.setStyleSheet("#list_of_equipment{\n"
"    background-color: transparent;\n"
"    border: 1px solid gray;\n"
"    color: white;\n"
"}")
        self.list_of_equipment.setObjectName("list_of_equipment")
        self.gridLayout_4.addWidget(self.list_of_equipment, 1, 0, 1, 1)
        self.tabWidget.addTab(self.equipment_tab, "")
        self.report_tab = QtWidgets.QWidget()
        self.report_tab.setStyleSheet("#report_tab{\n"
"background-color: #131936;\n"
"}")
        self.report_tab.setObjectName("report_tab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.report_tab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.list_of_reports = QtWidgets.QListWidget(parent=self.report_tab)
        self.list_of_reports.setStyleSheet("#list_of_reports{\n"
"    background-color: transparent;\n"
"    border: 1px solid gray;\n"
"    color: white;}\n"
"QListWidget::item {\n"
"    border-radius: 9px;\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #2b5876, stop: 1 #4e4376);\n"
"    min-height: 40px;\n"
"    margin: 3px;\n"
"}"
"QListWidget::item:hover {\n"
"    background-color: rgb(41, 85, 180);\n"
"}")
        self.list_of_reports.setObjectName("list_of_reports")
        self.gridLayout_5.addWidget(self.list_of_reports, 0, 0, 1, 1)
        self.tabWidget.addTab(self.report_tab, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Компьютерный клуб"))
        self.create_session_button.setText(_translate("MainWindow", "Создать сеанс"))
        self.select_hall.setPlaceholderText(_translate("MainWindow", "Зал"))
        self.loyal_system_button.setText(_translate("MainWindow", "Система лояльности"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.game_session_tab), _translate("MainWindow", "Игровые сеансы"))
        self.create_client_button.setText(_translate("MainWindow", "Добавить клиента"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.client_tab), _translate("MainWindow", "Клиенты"))
        self.create_equipment_button.setText(_translate("MainWindow", "Добавить оборудование"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.equipment_tab), _translate("MainWindow", "Оборудование"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.report_tab), _translate("MainWindow", "Отчеты"))
