# Form implementation generated from reading ui file 'report-page.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 270)
        MainWindow.setMinimumSize(QtCore.QSize(500, 270))
        MainWindow.setMaximumSize(QtCore.QSize(500, 500))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("#centralwidget{\n"
"background-color: #131936;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.create_report_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.create_report_button.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight SemiConde")
        font.setPointSize(14)
        self.create_report_button.setFont(font)
        self.create_report_button.setStyleSheet("#create_report_button{\n"
"    background-color: rgb(92, 17, 255);\n"
"    border-radius: 10px;\n"
"    color: white;\n"
"}")
        self.create_report_button.setObjectName("create_report_button")
        self.gridLayout.addWidget(self.create_report_button, 2, 0, 1, 1)
        self.report_name = QtWidgets.QLabel(parent=self.centralwidget)
        self.report_name.setStyleSheet("#report_name{\n"
"color: white;\n"
"background-color: transparent;\n"
"}")
        self.report_name.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.report_name.setObjectName("report_name")
        self.gridLayout.addWidget(self.report_name, 0, 0, 1, 1)
        self.report_description = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.report_description.setStyleSheet("#report_description{\n"
"    background-color: transparent;\n"
"    border: 1px solid gray;\n"
"    color: white;\n"
"}")
        self.report_description.setObjectName("report_description")
        self.gridLayout.addWidget(self.report_description, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Отчет"))
        self.create_report_button.setText(_translate("MainWindow", "Создать и сохранить отчет"))
        self.report_name.setText(_translate("MainWindow", "TextLabel"))
