# Form implementation generated from reading ui file 'set-hall-window.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(310, 200)
        MainWindow.setMinimumSize(QtCore.QSize(310, 200))
        MainWindow.setMaximumSize(QtCore.QSize(310, 200))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("#centralwidget{\n"
"background-color: #131936;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.hall_save_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.hall_save_button.setGeometry(QtCore.QRect(110, 100, 100, 35))
        self.hall_save_button.setMinimumSize(QtCore.QSize(100, 35))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight SemiConde")
        font.setPointSize(14)
        self.hall_save_button.setFont(font)
        self.hall_save_button.setStyleSheet("#hall_save_button{\n"
"    background-color: rgb(24, 148, 2);\n"
"}")
        self.hall_save_button.setObjectName("hall_save_button")
        self.hall_del_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.hall_del_button.setGeometry(QtCore.QRect(110, 140, 100, 35))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hall_del_button.sizePolicy().hasHeightForWidth())
        self.hall_del_button.setSizePolicy(sizePolicy)
        self.hall_del_button.setMinimumSize(QtCore.QSize(100, 35))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight SemiConde")
        font.setPointSize(14)
        self.hall_del_button.setFont(font)
        self.hall_del_button.setStyleSheet("#hall_del_button{\n"
"    background-color: rgba(255, 0, 0, 0.9);\n"
"}")
        self.hall_del_button.setObjectName("hall_del_button")
        self.layoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(31, 21, 251, 66))
        self.layoutWidget.setObjectName("layoutWidget")
        self.hallLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.hallLayout.setContentsMargins(0, 0, 0, 0)
        self.hallLayout.setObjectName("hallLayout")
        self.hallname_edit = QtWidgets.QLineEdit(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight SemiConde")
        font.setPointSize(14)
        self.hallname_edit.setFont(font)
        self.hallname_edit.setStyleSheet("#hallname_edit{\n"
"    background-color: transparent;\n"
"    border: 1px solid gray;\n"
"color: white;\n"
"}")
        self.hallname_edit.setMaxLength(30)
        self.hallname_edit.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.hallname_edit.setObjectName("hallname_edit")
        self.hallLayout.addWidget(self.hallname_edit, 0, 0, 1, 1)
        self.roominessLayout = QtWidgets.QHBoxLayout()
        self.roominessLayout.setObjectName("roominessLayout")
        self.roominess_hall_label = QtWidgets.QLabel(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight SemiConde")
        font.setPointSize(14)
        self.roominess_hall_label.setFont(font)
        self.roominess_hall_label.setStyleSheet("#roominess_hall_label{\n"
"color: white;\n"
"}")
        self.roominess_hall_label.setObjectName("roominess_hall_label")
        self.roominessLayout.addWidget(self.roominess_hall_label)
        self.roominess_hall_edit = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.roominess_hall_edit.setMinimumSize(QtCore.QSize(30, 30))
        self.roominess_hall_edit.setMaximumSize(QtCore.QSize(60, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight SemiConde")
        font.setPointSize(14)
        self.roominess_hall_edit.setFont(font)
        self.roominess_hall_edit.setStyleSheet("#roominess_hall_edit{\n"
"    background-color: transparent;\n"
"    border: 1px solid gray;\n"
"    color: white;\n"
"}")
        self.roominess_hall_edit.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.roominess_hall_edit.setObjectName("roominess_hall_edit")
        self.roominessLayout.addWidget(self.roominess_hall_edit)
        self.hallLayout.addLayout(self.roominessLayout, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Настройка залов"))
        self.hall_save_button.setText(_translate("MainWindow", "Сохранить"))
        self.hall_del_button.setText(_translate("MainWindow", "Удалить"))
        self.hallname_edit.setPlaceholderText(_translate("MainWindow", "Введите название зала"))
        self.roominess_hall_label.setText(_translate("MainWindow", "Количество мест:"))
        self.roominess_hall_edit.setInputMask(_translate("MainWindow", "999"))
