# Form implementation generated from reading ui file 'set-equipment-window.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(350, 280)
        MainWindow.setMinimumSize(QtCore.QSize(350, 280))
        MainWindow.setMaximumSize(QtCore.QSize(500, 400))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("#centralwidget{\n"
"background-color: #131936;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.equip_description = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.equip_description.setMinimumSize(QtCore.QSize(330, 110))
        self.equip_description.setMaximumSize(QtCore.QSize(500, 300))
        self.equip_description.setStyleSheet("#equip_description{\n"
"    background-color: transparent;\n"
"    border: 1px solid gray;\n"
" color: white;\n"
"}")
        self.equip_description.setObjectName("equip_description")
        self.gridLayout.addWidget(self.equip_description, 1, 0, 1, 2)
        self.set_hall_equip = QtWidgets.QComboBox(parent=self.centralwidget)
        self.set_hall_equip.setMinimumSize(QtCore.QSize(0, 30))
        self.set_hall_equip.setStyleSheet("#set_hall_equip{\n"
"    background-color: transparent;\n"
"    border: 1px solid gray;\n"
" color: white;\n"
"}"
"QListView {\n"
"    background-color: rgb(41, 85, 180);\n"
    "color: white;\n"
"}"
"QListView::item:selected {\n"
"    background-color: #131936;\n"
    "color: white;\n"
"}")
        self.set_hall_equip.setObjectName("set_hall_equip")
        self.gridLayout.addWidget(self.set_hall_equip, 2, 0, 1, 1)
        self.set_equip_place = QtWidgets.QComboBox(parent=self.centralwidget)
        self.set_equip_place.setMinimumSize(QtCore.QSize(0, 30))
        self.set_equip_place.setStyleSheet("#set_equip_place{\n"
"    background-color: transparent;\n"
"    border: 1px solid gray;\n"
" color: white;\n"
"}"
"QListView {\n"
"    background-color: rgb(41, 85, 180);\n"
    "color: white;\n"
"}"
"QListView::item:selected {\n"
"    background-color: #131936;\n"
    "color: white;\n"
"}")
        self.set_equip_place.setObjectName("set_equip_place")
        self.gridLayout.addWidget(self.set_equip_place, 3, 0, 1, 1)
        self.save_equip_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.save_equip_button.setMinimumSize(QtCore.QSize(100, 35))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight SemiConde")
        font.setPointSize(14)
        self.save_equip_button.setFont(font)
        self.save_equip_button.setStyleSheet("#save_equip_button{\n"
"    background-color: rgb(24, 148, 2);\n"
"    border-radius: 10px;\n"
"}")
        self.save_equip_button.setObjectName("save_equip_button")
        self.gridLayout.addWidget(self.save_equip_button, 3, 1, 1, 1)
        self.set_price_equip = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.set_price_equip.setMinimumSize(QtCore.QSize(0, 30))
        self.set_price_equip.setStyleSheet("#set_price_equip{\n"
"    background-color: transparent;\n"
"    border: 1px solid gray;\n"
"    color: white;\n"
"}")
        self.set_price_equip.setPlaceholderText('Цена аренды')
        self.set_price_equip.setInputMask("9999999.99")
        self.set_price_equip.setObjectName("set_price_equip")
        self.gridLayout.addWidget(self.set_price_equip, 4, 0, 1, 1)
        self.del_equip_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.del_equip_button.setMinimumSize(QtCore.QSize(100, 35))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight SemiConde")
        font.setPointSize(14)
        self.del_equip_button.setFont(font)
        self.del_equip_button.setStyleSheet("#del_equip_button{\n"
"    background-color: rgba(255, 0, 0, 0.9);\n"
"    border-radius: 10px;\n"
"}")
        self.del_equip_button.setObjectName("del_equip_button")
        self.gridLayout.addWidget(self.del_equip_button, 4, 1, 1, 1)
        self.set_category_equip = QtWidgets.QComboBox(parent=self.centralwidget)
        self.set_category_equip.setMinimumSize(QtCore.QSize(0, 30))
        self.set_category_equip.setStyleSheet("#set_category_equip{\n"
"    background-color: transparent;\n"
"    border: 1px solid gray;\n"
"    color: white;\n"
"}"
"QListView {\n"
"    background-color: rgb(41, 85, 180);\n"
    "color: white;\n"
"}"
"QListView::item:selected {\n"
"    background-color: #131936;\n"
    "color: white;\n"
"}")
        self.set_category_equip.setObjectName("set_category_equip")
        self.set_category_equip.addItems(['Компьютеры', 'Консоли', 'VR', 'Периферия', 'Другое'])
        self.set_category_equip.setCurrentIndex(-1)
        self.gridLayout.addWidget(self.set_category_equip, 0, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Оборудование"))
        self.equip_description.setPlaceholderText(_translate("MainWindow", "Введите описание для оборудования"))
        self.set_hall_equip.setPlaceholderText(_translate("MainWindow", "Выберите зал"))
        self.set_equip_place.setPlaceholderText(_translate("MainWindow", "Выберите место"))
        self.save_equip_button.setText(_translate("MainWindow", "Сохранить"))
        self.set_price_equip.setPlaceholderText(_translate("MainWindow", "Введите цену за час"))
        self.del_equip_button.setText(_translate("MainWindow", "Удалить"))
        self.set_category_equip.setPlaceholderText(_translate("MainWindow", "Выберите категорию оборудования"))
