# Form implementation generated from reading ui file 'set-gamesession-window.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(466, 350)
        MainWindow.setMaximumSize(QtCore.QSize(466, 500))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(466, 350))
        self.centralwidget.setMaximumSize(QtCore.QSize(800, 500))
        self.centralwidget.setStyleSheet("#centralwidget{\n"
"background-color: #131936;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.set_client = QtWidgets.QComboBox(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight SemiConde")
        font.setPointSize(14)
        self.set_client.setFont(font)
        self.set_client.setStyleSheet("#set_client{\n"
"    background-color: transparent;\n"
"    border: 1px solid gray;\n"
"    color: white;\n"
"}"
"QListView {\n"
"    background-color: rgb(41, 85, 180);\n"
    "color: white;\n"
"}"
"QListView::item:selected {\n"
"    background-color: #131936;\n"
    "color: white;\n"
"}"
)
        self.set_client.setEditable(False)
        self.set_client.setCurrentText("")
        self.set_client.setObjectName("set_client")
        self.set_client.setCurrentIndex(-1)
        self.gridLayout_2.addWidget(self.set_client, 0, 0, 1, 1)
        self.set_equipment = QtWidgets.QComboBox(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight SemiConde")
        font.setPointSize(14)
        self.set_equipment.setFont(font)
        self.set_equipment.setStyleSheet("#set_equipment{\n"
"    background-color: transparent;\n"
"    border: 1px solid gray;\n"
"    color: white;\n"
"}"
"QListView {\n"
"    background-color: rgb(41, 85, 180);\n"
    "color: white;\n"
"}"
"QListView::item:selected {\n"
"    background-color: #131936;\n"
    "color: white;\n"
"}")
        self.set_equipment.setCurrentIndex(-1)
        self.set_equipment.setObjectName("set_equipment")
        self.gridLayout_2.addWidget(self.set_equipment, 1, 0, 1, 1)
        self.equipment_info = QtWidgets.QTextBrowser(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight SemiConde")
        font.setPointSize(12)
        self.equipment_info.setFont(font)
        self.equipment_info.setStyleSheet("#equipment_info{\n"
"    background-color: transparent;\n"
"    border: 1px solid gray;\n"
"    color: white;\n"
"}")
        self.equipment_info.setObjectName("equipment_info")
        self.gridLayout_2.addWidget(self.equipment_info, 2, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.time_session_edit = QtWidgets.QTimeEdit(parent=self.centralwidget)
        self.time_session_edit.setMinimumSize(QtCore.QSize(100, 30))
        self.time_session_edit.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight SemiConde")
        font.setPointSize(14)
        self.time_session_edit.setFont(font)
        self.time_session_edit.setStyleSheet("#time_session_edit{\n"
"    background-color: transparent;\n"
"    border: 1px solid gray;\n"
"    color: white;\n"
"}")
        self.time_session_edit.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.time_session_edit.setObjectName("time_session_edit")
        self.gridLayout.addWidget(self.time_session_edit, 0, 0, 1, 1)
        self.stop_session_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.stop_session_button.setMinimumSize(QtCore.QSize(100, 35))
        self.stop_session_button.setMaximumSize(QtCore.QSize(200, 35))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight SemiConde")
        font.setPointSize(14)
        self.stop_session_button.setFont(font)
        self.stop_session_button.setStyleSheet("#stop_session_button{\n"
"    background-color: rgba(255, 0, 0, 0.9);\n"
"    border-radius: 10px;\n"
"}")
        self.stop_session_button.setObjectName("stop_session_button")
        self.gridLayout.addWidget(self.stop_session_button, 1, 2, 1, 1)
        self.price_session = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.price_session.setMinimumSize(QtCore.QSize(100, 30))
        self.price_session.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight SemiConde")
        font.setPointSize(14)
        self.price_session.setFont(font)
        self.price_session.setReadOnly(True)
        self.price_session.setStyleSheet("#price_session{\n"
"    background-color: transparent;\n"
"    border: 1px solid gray;\n"
"    color: white;\n"
"}")
        self.price_session.setObjectName("price_session")
        self.gridLayout.addWidget(self.price_session, 1, 0, 1, 1)
        self.save_session_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.save_session_button.setMinimumSize(QtCore.QSize(100, 35))
        self.save_session_button.setMaximumSize(QtCore.QSize(200, 35))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight SemiConde")
        font.setPointSize(14)
        self.save_session_button.setFont(font)
        self.save_session_button.setStyleSheet("#save_session_button{\n"
"    background-color: rgb(24, 148, 2);\n"
"    border-radius: 10px;\n"
"}")
        self.save_session_button.setObjectName("save_session_button")
        self.gridLayout.addWidget(self.save_session_button, 0, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 3, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Игровой сеанс"))
        self.set_client.setPlaceholderText(_translate("MainWindow", "Выберите клиента"))
        self.set_client.setItemText(0, _translate("MainWindow", "Что то"))
        self.set_client.setItemText(1, _translate("MainWindow", "Еще"))
        self.set_equipment.setPlaceholderText(_translate("MainWindow", "Выберите устройство"))
        self.stop_session_button.setText(_translate("MainWindow", "Завершить сеанс"))
        self.save_session_button.setText(_translate("MainWindow", "Сохранить"))
